### ISSUE TITLE
FAQ: How to create a unique username mapper for an idp

### ISSUE THREAD

**Issue by patricksimonian** [bcgov/ocp-sso#189] opened 2021-03-03 00:10 UTC
**Describe the issue**
> https://chat.developer.gov.bc.ca/channel/sso?msg=2AJpfNqWdnvB5aRuj
When using VC on a newly provisioned realm I am being prompted with the message about a user with the same email address already existing in the database.

**Additional context**
After some discovery this found to be caused by the VC role mapping having no entry for username. It would create accounts with blank usernames. 

**The Fix**

You should always map an absolutely unique value to the username mapping **EMAIL** is not unique!. The challenge with VC is that the unique values found as claims are not accessible when creating the role mapping. Things like 
`${CLAIM.sub}` or any other standard oidc claim are not accessible. 

If you take a look at the [keycloak code base](https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/broker/oidc/mappers/UsernameTemplateMapper.java#L171) (thanks @arcshiftsolutions !) you'll find there is a use case to generate UUIDs!

in the mapper you can enter `${UUID}` to generate a UUID.

More discovery is required for why standard claims can't be used as a mapper for VC.

**Comment by esune** [comment] 2021-03-03 00:21
Note: the above is true not only for VCs, but for any IdP that for some reason will not provide a unique user identifier upon successful authentication.

In the specific case of VCs, the complexity is in the fact that the same IdP ([vc-authn-oidc](https://github.com/bcgov/vc-authn-oidc)) is used to perform authentication responding to different proof-requests that require different VCs. In this case:
- the unique identifier *MAY* be provided as an attribute by the VC, but this is not guaranteed
- the unique identifier will likely be held by a differently named attribute for each VC

There is a way of binding the value f the unique identifier - if provided by the VC - to the standard `sub` field of an OIDC token, however it is true that standard fields don't seem to be processable by the username preprocessor in Keycloak.

Another thing worth noting in the case of VCs is that no `authorization_token` is provided by the IdP, only an `id_token` is generated: this is by design, since the VC IdP is not meant to perform any type of authorization check other than verifying the credentials that were received are valid.

**Comment by zsamji** [comment] 2022-01-05 20:40
closing as it is captured: https://github.com/bcgov/sso-keycloak/discussions/66

**Closed by zsamji** 2022-01-05 20:40 UTC
Labels: FAQ, sso
